version: '3.8'
volumes:
  static:
services:
  proxy:
    image: nginx:1.20
    container_name: proxy
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    external:
      name: timeweeb
