version: '3.8'
volumes:
  static:
services:
  proxy:
    image: nginx:1.20
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/web
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
networks:
  default:
    external:
      name: timeweeb
